{{ if and (not .Values.azp.existingSecret) (not .Values.azp.existingSecretKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azp-agent-autoscaler.fullname" . }}
  labels:
    {{- include "azp-agent-autoscaler.labels" . | nindent 4 }}
type: Opaque
data:
  azp-token: {{ .Values.azp.token | required "The Azure Pipeline Token is required!" | b64enc | quote }}
{{ end }}
