{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azp-agent-autoscaler.fullname" . | quote }}
  labels:
    {{- include "azp-agent-autoscaler.labels" . | nindent 4 }}
{{ end }}
