{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azp-agent-autoscaler.fullname" . | quote }}
  labels:
    {{- include "azp-agent-autoscaler.labels" . | nindent 4 }}
    {{- include "azp-agent-autoscaler.stringDict" .Values.serviceAccount.labels | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- include "azp-agent-autoscaler.stringDict" .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{ end }}
